
# testing YAML validation for itemCode field

#Astina\TodoBundle\Entity\Todo:
#  properties:
#    itemCode:
#      - Range:
#          min: 1
#          max: 200
#          minMessage: You must be above 1
#          maxMessage: You must be below 200